### PR TITLE
feat: support kugou,kuwo music share

### PR DESCRIPTION
**Pull request by wdvxdr1123**
新加两种类型

### CODE REVIEW

**Review by Him188 — APPROVED** [review]

**Comment by Him188** [comment]
Thank you!

**Comment by Him188** [comment]
我会在稍后添加 `@since 2.7` 文档注释然后合并

**Comment by Karlatemp** [comment]
Tested?

**Comment by wdvxdr1123** [comment]
test in miraigo three months ago
Mrs4s/MiraiGo#111

**Review by Karlatemp — APPROVED** [review]

**Review by Him188 — APPROVED** [review]

**Pull request merged**
